export const ISLETME_KATEGORILER = [
  'Güzellik Merkezi',
  'Bayan Kuaför',
  'Erkek Kuaför / Berber',
  'Kuaför (Uniseks)',
  'Tırnak Bakım Merkezi',
  'Dövme & Tattoo Merkezi',
  'Piercing Stüdyosu',
  'Spa & Wellness Merkezi',
  'Masaj Salonu',
  'Epilasyon & Lazer Merkezi',
  'Cilt Bakım Merkezi',
  'Medikal Estetik Kliniği',
  'Saç Ekimi Merkezi',
  'Hamam & Kese',
  'Pilates & Yoga Stüdyosu',
  'Fitness & Spor Salonu',
  'Diğer',
]
